### ISSUE TITLE
MacOS: could not locate any Comsol installation

### ISSUE THREAD

**Issue by pozzato** [MPh-py/MPh#147]
Hello,

I've installed the latest version of MPh (1.2.3) on a MacBook Pro M2 (Ventura 13.5), with COMSOL 6.0 installed. Comsol  is installed inside /Applications/COMSOL60/Multiphysics (the default path).

When I start the client, I get the following error:
_Could not locate any Comsol installation.
1.2.3
Traceback (most recent call last):

  File ~/anaconda3/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/.spyder-py3/temp.py:21
    client = mph.start()

  File ~/anaconda3/lib/python3.11/site-packages/mph/session.py:103 in start
    server = Server(cores=cores, version=version, port=port)

  File ~/anaconda3/lib/python3.11/site-packages/mph/server.py:85 in __init__
    backend = discovery.backend(version)

  File ~/anaconda3/lib/python3.11/site-packages/mph/discovery.py:415 in backend
    raise RuntimeError(error)

RuntimeError: Could not locate any Comsol installation._

I am aware that this issue was highlighted in the past (and it should have been resolved with version 1.1.4), however, do you know the source of this error?  

Thanks

**Comment by john-hen** [comment]
No, this is not the issue that was resolved in 1.1.4. Support for ARM-based Comsol installations on macOS was never added, see [Installation](https://mph.readthedocs.io/en/1.2/installation.html#comsol) chapter in the documentation, and issue #80, of which this is a duplicate.
