### ISSUE TITLE
Occupy unnecessary license type 

### ISSUE THREAD

**Issue by bwutdk** [MPh-py/MPh#153]
The comsol main file is using "MEMS " license, when I run the code below it will hold "Acoustic" license too, but I didn't need it.  
it works fine just need to know how to release the "Acoustic" license for other team members.

client = mph.start(version='6.0')
pymodel = client.load(Input_COMSOL_name)
model = pymodel.java 

Thank you

**Comment by john-hen** [comment]
MPh does not check out any licenses. This happens when the Comsol client loads your model and inspects it. MPh has nothing to do with that process.
