### ISSUE TITLE
RuntimeError: Could not locate any Comsol installation. OS X

### ISSUE THREAD

**Issue by JohannesScheyerle** [MPh-py/MPh#174]
Hey there,

it seems like MPh is going to lift up my COMSOL process quite big, so thanks for that in advanve!

I have the same issue like
https://github.com/MPh-py/MPh/issues/71

But I am using OS X and my comsol location is 

/Applications/COMSOL61/Multiphysics/

And I don't know where the installers default location for COMSOL is in OS X and how I change my location.

Thanks for you help in advance!

**Comment by john-hen** [comment]
Hi. That's not the same issue, just the same error message. (Which I'll have to change to "Could not find a *compatible* Comsol installation".)

More likely, you've run into issue #80.

**Comment by JohannesScheyerle** [comment]
Hey. Thanks for this tip. I tried replacing "maci64" with "macarm64" or add "macarm64" to the architectures list on line 42, but it's a bit strange for me. I am new to all this so sorry in advance:
I only can find exactly one instance of "maci64" in discovery.py and this is line 42. Why did people find more? So should I add or replace "macarm64" in line 42. I already tried a few options and it did not work. But it worked for other people. And since I am a little noob in such things, could you provide a step by step guide to what to do, or maybe even or only the exact syntax for line 42?

Thanks a lot!

**Comment by JohannesScheyerle** [comment]
nevermind. I found 2 places where mph was installed so i also found 2 discovery.py files. Changed both and it worked. Thanks you so much for mph!! :)
