### ISSUE TITLE
Mph-py doesn't work with manually loaded to Comsol packages

### ISSUE THREAD

**Issue by Jristina** [MPh-py/MPh#189]
Exception:
        com.comsol.util.exceptions.FlException: Unknown physics interface
Messages:
        Unknown physics interface
        - Physics interface: MicromagneticsFrequencyDomain
        

Please, fix this, I'd like to use Mph-py with Micromagnetics package!

**Comment by john-hen** [comment]
I don't know what you're talking about, "manually loaded to Comsol packages". That error is raised by Comsol, not MPh. I don't know how you managed to have a model with an "unknown" physics interface, but MPh does not deal with the physics interfaces anyway. It just tell Comsol to load the model, Comsol then looks at the model file and loads whatever else may be needed. In your case, it fails with that error.

**Comment by john-hen** [comment]
Closed: not reproducible.
