### ISSUE TITLE
RuntimeError: Could not find a supported Comsol installation

### ISSUE THREAD

**Issue by vharsha12** [MPh-py/MPh#191]
Hi, 

I am in the process of using MPh 1.2.4 with Comsol 6.2 in Linux. In doing so, I see an error message as follows: RuntimeError: Could not find a supported Comsol installation.

I did go through some of the archived issues, but it was for Comsol version 6.0. 

Sorry, a bit new here and looking for guidance. 

Thank you very much in advane!

**Comment by john-hen** [comment]
Hi. Whether it's Comsol 6.2 or 6.0 doesn't matter. Some guidance is provided in [Installation](https://mph.readthedocs.io/en/1.2/installation.html#comsol) section of the docs. I don't know how you installed Comsol, but it may not be in its default location on your Linux system.
