### ISSUE TITLE
RuntimeError: Could not locate any Comsol installation.

### ISSUE THREAD

**Issue by Chaztikov** [MPh-py/MPh#71]
Hi, and thanks for making MPh.

I'm looking forward to using this, but, at the moment, I'm getting the error below, not sure how to fix this.  Is there a way to directly specify where Comsol is installed?

In my case, I have comsol 6.0 installed on Ubuntu Linux 18.04 under

/usr/local/bin/comsol60/multiphysics/

Thanks

```
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> client = mph.start(cores=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mph' is not defined
>>> import mph
>>> client = mph.start(cores=1)
Could not locate any Comsol installation.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chaztikov/.local/lib/python3.6/site-packages/mph/session.py", line 102, in start
    server = Server(cores=cores, version=version, port=port)
  File "/home/chaztikov/.local/lib/python3.6/site-packages/mph/server.py", line 77, in __init__
    backend = discovery.backend(version)
  File "/home/chaztikov/.local/lib/python3.6/site-packages/mph/discovery.py", line 417, in backend
    raise RuntimeError(error)
RuntimeError: Could not locate any Comsol installation.
>>> 
```

**Comment by john-hen** [comment]
Hi. What version of MPh are you using? For all I know, I just fixed that very problem day before yesterday, in version 1.1.4. See issue #67.

**Comment by Chaztikov** [comment]
Thanks for responding! I'll take a look at #67.

>>> mph.__version__
'1.1.4'

**Comment by Chaztikov** [comment]
Hmm the test under tools doesn't seem to be working for me


chaztikov@liberty:~/git/MPh/tools$ python3 test.py discovery --log
Running test group "discovery".
[00:00.210] Could not locate any Comsol installation.
Traceback (most recent call last):
  File "test_discovery.py", line 40, in <module>
    test_backend()
  File "test_discovery.py", line 25, in test_backend
    backend = mph.discovery.backend()
  File "/home/chaztikov/git/MPh/mph/discovery.py", line 417, in backend
    raise RuntimeError(error)
RuntimeError: Could not locate any Comsol installation.
Failed after 0 s.

Also, tried after pulling and reinstalling MPh more directly 
cd ~/git/MPh
pip3 install .

Just checking that the version is 1.1.4 as I expected 

chaztikov@liberty:~/git/MPh/tools$ python3
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mph
>>> mph.__version__
'1.1.4'

**Comment by john-hen** [comment]
Ah, so you're on the latest version. But I just realized that you have Comsol installed in a custom location. The installer defaults to `/usr/local/comsol60`, but you have it `/usr/local/bin/comsol60`. You don't have re-install, you can create a symbolic link to the installation folder in `~/.local`. (See also chapter [Installation](https://mph.readthedocs.io/en/1.1/installation.html).)

**Comment by Chaztikov** [comment]
Thank you! That did the trick!
