### ISSUE TITLE
`AttributeError` raised when running multiple processes

### ISSUE THREAD

**Issue by qigesmn** [MPh-py/MPh#76]
Hey, dear john, thanks again for sharing this wonderful work!
I had run a orthogonal test in a script, to avoid the  extremely long runtime but not raising exception during a iteration, I put the code \"model.solve()\" into Multiprocessing.Process just like following
def _solve():
    global model
    model.solve()

p = Multiprocessing.Process(_solve)
p.start()

The script raise
"""
File \"<string>\", line 1, in <module>
File \"D:\anaconda\lib\multiprocessing\spawn.py\", line 105, in spawn_main
    exitcode = _main(fd)
 File \'D:\anaconda\lib\multiprocessing\spawn.py\', line 115, in _main
    self = reduction.pickle.load(from_parent)
 AttributeError: Can't get attribute \'_solve\' on <module \'__mp_main__\' from {__file__}.>
"""

**Comment by john-hen** [comment]
Hi, and you're welcome.
This isn't the complete script though, so I cannot reproduce the problem. But did you go through the section ["Multiple processes"](https://mph.readthedocs.io/en/stable/demonstrations.html#multiple-processes) in the documentation? It has some advice that might be helpful. Or you start from the demo script [`worker_pool.py`](https://github.com/MPh-py/MPh/blob/main/demos/worker_pool.py), and then add your code. If don't see you fencing the main entry point with `if __name__ == '__main__'`, which is a common stumbling block when doing multiprocessing (on Windows).

**Comment by qigesmn** [comment]
Hi, thanks for effective suggestions.
My original intention is to use Multiprocessing.Process to react between computing-thread and monitoring-thread, so as to avoid endless one-step iteration.I tried my original scripts which different from #[worker_pool.py](https://github.com/MPh-py/MPh/blob/main/demos/worker_pool.py) in Ubuntu 18.04 and succeeded, but in platform win10 failed. I I guess it may be incompatibility of multiprocessing between linux and windows. I have retested the modified script referring to your demo and succeeded. The code I will release the mentioned code to you soon.
Anyways, thanks again for this useful package!

**Comment by qigesmn** [comment]
`
import mph
import multiprocessing
import queue
import numpy as np
import pandas as pd
import time


values = list(np.arange(0.5, 5.5, 0.5))
nprocesses = 1
global_cores = 2
cores_per_process = global_cores // nprocesses
required_solving_expression = ('2*es.intWe/U^2', 'pF')

jobs = multiprocessing.Queue()

def worker(jobs, results):
    client = mph.start(cores=cores_per_process)
    model = client.load('capacitor.mph')
    global required_solving_expression
    while True:
        try:
            d = jobs.get(block=False)
        except queue.Empty:
            break
        model.parameter('d', f'{d}[mm]')
        model.solve('static')
        C = model.evaluate(*required_solving_expression)
        results.put((d, C))

        
jobs = multiprocessing.Queue()
for d in values:
    jobs.put(d)
results = multiprocessing.Queue()

processes = []

for _ in range(nprocesses):
    processes.append(multiprocessing.Process(target=worker, args=(jobs, results)))
    processes[-1].start()
    
    
MAX_LAG_THRESHOLD = 20

start_time = time.time()
time.sleep(1)
duration_time = time.time()

start_queue_count = 0

while True:
    if processes[-1].is_alive() & (duration_time - start_time < MAX_LAG_THRESHOLD):
        time.sleep(0.5)
        tmp_queue_count = results.qsize()
        duration_time = time.time()
        if tmp_queue_count != start_queue_count:
            start_time = time.time()
            duration_time = time.time()
            start_queue_count = tmp_queue_count
    elif processes[-1].is_alive() & (duration_time - start_time >= MAX_LAG_THRESHOLD):
        processes[-1].terminate()
        del processes[-1]
        processes.append(multiprocessing.Process(target=worker, args=(jobs, results)))
        processes[-1].start()
        start_time = time.time()
        duration_time = time.time()
    else:
        break

output = []
while results.qsize() > 0:
    output.append(results.get(block=False))
output`

The naive homemade code  is to kill  single extremely long runtime task during sweeping iterations, like optimal params search. There is only one calculative process, which using 14 cores because of limited cpu resource in providing script.It may be helpful to  unconstrained or constrained optimization tasks with unknown derivative function.
Thanks again for this package, wish you a good life!

**Comment by qigesmn** [comment]
```
import mph
import multiprocessing
import queue
import numpy as np
import pandas as pd
import time


values = list(np.arange(0.5, 5.5, 0.5))
nprocesses = 1
global_cores = 2
cores_per_process = global_cores // nprocesses
required_solving_expression = ('2*es.intWe/U^2', 'pF')

jobs = multiprocessing.Queue()

def worker(jobs, results):
    client = mph.start(cores=cores_per_process)
    model = client.load('capacitor.mph')
    global required_solving_expression
    while True:
        try:
            d = jobs.get(block=False)
        except queue.Empty:
            break
        model.parameter('d', f'{d}[mm]')
        model.solve('static')
        C = model.evaluate(*required_solving_expression)
        results.put((d, C))

        
jobs = multiprocessing.Queue()
for d in values:
    jobs.put(d)
results = multiprocessing.Queue()

processes = []

for _ in range(nprocesses):
    processes.append(multiprocessing.Process(target=worker, args=(jobs, results)))
    processes[-1].start()
    
    
MAX_LAG_THRESHOLD = 20

start_time = time.time()
time.sleep(1)
duration_time = time.time()

start_queue_count = 0

while True:
    if processes[-1].is_alive() & (duration_time - start_time < MAX_LAG_THRESHOLD):
        time.sleep(0.5)
        tmp_queue_count = results.qsize()
        duration_time = time.time()
        if tmp_queue_count != start_queue_count:
            start_time = time.time()
            duration_time = time.time()
            start_queue_count = tmp_queue_count
    elif processes[-1].is_alive() & (duration_time - start_time >= MAX_LAG_THRESHOLD):
        processes[-1].terminate()
        del processes[-1]
        processes.append(multiprocessing.Process(target=worker, args=(jobs, results)))
        processes[-1].start()
        start_time = time.time()
        duration_time = time.time()
    else:
        break

output = []
while results.qsize() > 0:
    output.append(results.get(block=False))
output
```

The naive homemade code  is to kill  single extremely long runtime task during sweeping iterations, like optimal params search. There is only one calculative process, which using 2 cores because of limited cpu resource in providing script. It may be helpful to  unconstrained or constrained optimization tasks with unknown derivative function.
Thanks again for this package, wish you a good life!

**Comment by qigesmn** [comment]
> 

The script is jupyter notebook style.
