### ISSUE TITLE
Java/Python boolean issue fix

### ISSUE THREAD

**Issue by banduser** [MPh-py/MPh#79]
Hey Jon,

I'm currrently using MPH to access the Java Layer of COMSOL directly in order to change the parameters of a model. 

 So far, in order to change my model I've been saving my COMSOL model as a .java file and copying lines of code, then adding  '.java' after 'model' and running the code in python. 

So for example:

 `model.param().set("box_width", "100 [mm]");`

becomes

 `model.java.param().set("box_width", "100 [mm]");`

This works great for changing Geometry Parameters, however, I've run into a seemingly minor issue when attempting to change certain Options in Comsol:

![grafik](https://user-images.githubusercontent.com/101814714/168070016-37211623-4928-4ce9-b3b4-f25112287b79.png)

Lets say I check the box marked 'Selections' in the image above and then copy the java code into my python script, I get

`model.component("comp1").mesh("mesh1").export().set("selection", true);`

which I can change to 

`model.java.component("comp1").mesh("mesh1").export().set("selection", true);`

but get an error when running the code in python because the boolean operators for python are capitalized ('True' instead of 'true'). This leads to python reading 'true' as an unnamed variable and results in an error. Changing the boolean operator to python Syntax This results in a COMSOL error however:

`model.java.component("comp1").mesh("mesh1").export().set("selection", true);`

`Traceback (most recent call last):

  File "C:\Users\me\Desktop\Mph_Test_Param.py", line 53, in <module>
    model.java.component("comp1").mesh("mesh1").export().set("selection", True);

TypeError: Ambiguous overloads found for com.comsol.model.impl.PropFeatureImpl.set(str,bool) between:
	public com.comsol.model.PropFeature com.comsol.model.impl.PropFeatureImpl.set(java.lang.String,boolean)
	public com.comsol.model.PropFeature com.comsol.model.impl.PropFeatureImpl.set(java.lang.String,int)`

I've found a fix for this using JPype with the argument jpype.java.lang.Boolean(True):

`model.java.component("comp1").mesh("mesh1").export().set("selection", jpype.java.lang.Boolean(True);` 

Just wanted to include this here incase anyone runs into the same issue.

**Comment by john-hen** [comment]
Thanks for documenting this here. It happens because in Python `bool` is a subclass of `int`, and JPype treats them the same and then cannot decide which of the two overloaded methods to call. Instead of `jpype.java.lang.Boolean` you can also use `jpype.JBoolean` to cast to a Java bool.
