### ISSUE TITLE
”RuntimeError: Could not locate any Comsol installation“  on macos

### ISSUE THREAD

**Issue by doub1emint** [MPh-py/MPh#83]
Hi,
thanks for developing mph, I'm getting this error below at the moment and don't know how to fix it.

in my case, I have comsol 6.0 installed in macOS 12.2.1 and the version of mph is 1.1.5.

comsol installation file is "/Applications/COMSOL60/Multiphysics"
here is the message:

`Could not locate any Comsol installation.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [20], in <cell line: 1>()
----> 1 client = mph.start()

File ~/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/mph/session.py:102, in start(cores, version, port)
    100     client = Client(cores=cores, version=version)
    101 elif session == 'client-server':
--> 102     server = Server(cores=cores, version=version, port=port)
    103     client = Client(cores=cores, version=version, port=server.port)
    104 else:

File ~/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/mph/server.py:78, in Server.__init__(self, cores, version, port, multi, timeout)
     74 def __init__(self, cores=None, version=None, port=None,
     75                    multi=None, timeout=60):
     76 
     77     # Start Comsol server as an external process.
---> 78     backend = discovery.backend(version)
     79     server  = backend['server']
     80     log.info('Starting external server process.')

File ~/opt/anaconda3/envs/py3.9/lib/python3.9/site-packages/mph/discovery.py:417, in backend(version)
    415     error = 'Could not locate any Comsol installation.'
    416     log.error(error)
--> 417     raise RuntimeError(error)
    418 if version is None:
    419     numbers = [(backend['major'], backend['minor'], backend['patch'],
    420                backend['build']) for backend in backends]

RuntimeError: Could not locate any Comsol installation.`

**Comment by doub1emint** [comment]
[ehsanhaghighat](https://github.com/ehsanhaghighat) suggestion can solve this problem.

**Comment by rtmr** [comment]
@doub1emint 
Hi.
I am in the same situation and would like to know about the following.
>ehsanhaghighat's suggestion can solve this problem.
I am sorry.
